language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: dhoucgitter
  api: https://api.run.pivotal.io
  organization: houck.dave-org
  space: development
  password:
    secure: xQ4pGkzq/2rfRP3wRgWQkfu0zmre3hbLGoyvEZ/qCmWZcHlexrdEIKMfQTHRrKSLWmohxjJBX9LqkLyQmf83fg8UPixjUCa176ZWYST9GtBUlNzJjt4Vx7TX+kXuAv42JlyWuHHFVIhRqu9fId7egBkU85kuhGfwobhdD7sdQ1YyD0IjdpEDz8P9HXmux2pfDtdR/0k8Kn7KCE5aLDTI36WXQ5M5KhgLf+0Yzg2AlSkyrju7ME6eozEG4OLNGtiJkAg1v0aBEZ8R1+HPI4AgukGNicd/ELqCNkgAcoBGLdN2gyHL8eDsosnI+nsrDCQ1/L5XneBQs/S7mYJ7w/YPL15hwdiXHJDvvAIwsCMLbW/oeBAuSTI5/u4knSDoPy8C4aGMjsMvrk+QlbZYmix2XLubZTCx7qxDRbjwD9hEKZ4uLyWj0FNNZLNOEO45STAbNeAt/iRUd8gP5maQWd+hJzvEmeiRas26Y/w4G59UIwI6hlMEuOFMG2ZHc24W5NLulopDhm141RMK11jeXYZ3UKv7McTvS6AGbuz3myHsiNRUtkXgUWSiQGPJ3KoIeaahrnM52+RXsyYaGIgoeMpoIqjbG4ZY7zOb9DK6pxYvfeW6ekH1mLhJpmps0HFJMDd99C5OCqoyDemQYGMKvDeqADjWGATPNziKau0EZRMlq68=
