language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: dhoucgitter 
  api: https://api.run.pivotal.io
  organization: houck.dave-org
  space: development